on:
  push:
    branches:
      - main

name: github-pages

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      pages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - uses: actions/deploy-pages@v4
